package com.po4yka.ratatoskr.util.perf

import kotlin.test.Test
import kotlin.test.assertEquals

class BaselineProfileEntryTest {
    @Test
    fun `class-only rule with no flags — parsed Rule with empty flags`() {
        // Bare descriptor with no flag prefix — least-restrictive form.
        val out = BaselineProfileEntry.parse("Lcom/po4yka/ratatoskr/MainActivity;")
        assertEquals(
            BaselineProfileLine.Rule(
                flags = emptySet(),
                classDescriptor = "Lcom/po4yka/ratatoskr/MainActivity;",
                member = null,
            ),
            out,
        )
    }

    @Test
    fun `Hot Startup PostStartup flag set — all three captured`() {
        val out = BaselineProfileEntry.parse("HSPLcom/po4yka/ratatoskr/MainActivity;")
        assertEquals(
            BaselineProfileLine.Rule(
                flags = setOf(RuleFlag.Hot, RuleFlag.Startup, RuleFlag.PostStartup),
                classDescriptor = "Lcom/po4yka/ratatoskr/MainActivity;",
                member = null,
            ),
            out,
        )
    }

    @Test
    fun `method rule with arrow and signature — flags and member parsed`() {
        // Pin the AOT-compilation-target shape used most often in
        // generated profiles: `HSPLClass;->method(args)Return`.
        val out =
            BaselineProfileEntry.parse(
                "HSPLcom/po4yka/ratatoskr/MainActivity;->onCreate(Landroid/os/Bundle;)V",
            )
        assertEquals(
            BaselineProfileLine.Rule(
                flags = setOf(RuleFlag.Hot, RuleFlag.Startup, RuleFlag.PostStartup),
                classDescriptor = "Lcom/po4yka/ratatoskr/MainActivity;",
                member = "onCreate(Landroid/os/Bundle;)V",
            ),
            out,
        )
    }

    @Test
    fun `comment line starting with hash — Comment`() {
        assertEquals(BaselineProfileLine.Comment, BaselineProfileEntry.parse("# generated by profileinstaller"))
    }

    @Test
    fun `blank line — Blank`() {
        assertEquals(BaselineProfileLine.Blank, BaselineProfileEntry.parse(""))
        assertEquals(BaselineProfileLine.Blank, BaselineProfileEntry.parse("   "))
    }

    @Test
    fun `descriptor must start with L — otherwise Invalid`() {
        // Defensive: a malformed profile (e.g. a class name without the
        // `L` JVM descriptor prefix) should not be silently treated as a
        // rule, since profileinstaller would reject it at compile time.
        assertEquals(BaselineProfileLine.Invalid, BaselineProfileEntry.parse("com/po4yka/ratatoskr/Foo;"))
    }

    @Test
    fun `descriptor must end with semicolon — otherwise Invalid`() {
        assertEquals(BaselineProfileLine.Invalid, BaselineProfileEntry.parse("Lcom/po4yka/ratatoskr/Foo"))
    }

    @Test
    fun `whitespace around the line is tolerated`() {
        val out = BaselineProfileEntry.parse("  Lcom/po4yka/ratatoskr/Foo;  ")
        assertEquals(
            BaselineProfileLine.Rule(
                flags = emptySet(),
                classDescriptor = "Lcom/po4yka/ratatoskr/Foo;",
                member = null,
            ),
            out,
        )
    }

    @Test
    fun `unknown flag character before L — Invalid`() {
        // A junk character before the descriptor is a sign of a corrupt
        // line, not a future-flag — reject so the profile reader can
        // surface the bad line rather than silently dropping it.
        assertEquals(BaselineProfileLine.Invalid, BaselineProfileEntry.parse("XLcom/po4yka/ratatoskr/Foo;"))
    }

    @Test
    fun `parse is deterministic`() {
        val a = BaselineProfileEntry.parse("HLcom/po4yka/ratatoskr/Foo;")
        val b = BaselineProfileEntry.parse("HLcom/po4yka/ratatoskr/Foo;")
        assertEquals(a, b)
    }
}
